# Generated by Django 5.1.5 on 2025-03-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('precipitation_sum', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HourlyWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('temperature_2m', models.FloatField()),
                ('relative_humidity_2m', models.FloatField()),
                ('soil_moisture_1_to_3cm', models.FloatField()),
                ('precipitation_probability', models.FloatField()),
            ],
        ),
    ]
